### ISSUE TITLE
这个报错是什么问题，无法连接api吗，请问如何解决

### ISSUE THREAD

**Issue by wfniub** [nxtrace/NTrace-dev#1]
![image](https://github.com/tsosunchia/nexttrace-core/assets/59757806/fa29b7f4-0542-4acc-b9b0-5760ca445ca1)

**Comment by tsosunchia** [comment]
> ![image](https://user-images.githubusercontent.com/59757806/243588112-fa29b7f4-0542-4acc-b9b0-5760ca445ca1.png)

https://github.com/sjlleo/nexttrace-core/issues/131#issuecomment-1579145769
