### ISSUE TITLE
路由追踪，中间全是*号

### ISSUE THREAD

**Issue by crosspacific** [nxtrace/NTrace-dev#12]
## 你正在使用哪个版本的 nexttrace？

NTrace-V1  v1.2.1.1   nexttrace_windows_amd64.exe

## 你看到的异常现象是什么？

路由追踪中间是*号

![screenshot20230924](https://github.com/nxtrace/NTrace-V1/assets/48462348/5ddce841-8775-4dd6-9048-682d73a45577)

## 你期待看到的正常表现是怎样的？

正常的路由追踪

## 请附上你的命令

nexttrace 8.222.197.62

## 是否查询过本仓库wiki有没有类似错误

查寻过wiki和issue，无论是手动在网络防火墙里添加，还是执行代码添加，路由追踪只有首尾，中间全部为*****
![screenshot20230924 (1)](https://github.com/nxtrace/NTrace-V1/assets/48462348/c108951e-6dd3-4e0a-888e-4013bf913052)

**Comment by tsosunchia** [comment]
https://github.com/nxtrace/NTrace-core/issues/52#issuecomment-1732502451
