### ISSUE TITLE
在有本地代理的情况下设置NEXTTRACE_PROXY环境变量之后出现{"error":"Wrong request_id"}错误

### ISSUE THREAD

**Issue by qclucky7** [nxtrace/NTrace-dev#25]
## 你正在使用哪个版本的 nexttrace？

window amd64

## 你看到的异常现象是什么？

设置代理后出现
NextTrace v1.2.4.2 2023-11-13T08:54:01Z 98c0fa3
{"error":"Wrong request_id"}

RetToken failed 3 times, please try again after a while, exit

## 请附上出错时软件输出的错误信息
NextTrace v1.2.4.2 2023-11-13T08:54:01Z 98c0fa3
{"error":"Wrong request_id"}

RetToken failed 3 times, please try again after a while, exit

## 是否查询过本仓库wiki有没有类似错误
是

**Comment by tsosunchia** [comment]
请提供一下，你设置ENV的命令，是不是这里配置错了

**Comment by tsosunchia** [comment]
另外如果你的Windows中装有WSL，也可以实验一下，同样的ENV在WSL下使用nexttrace是否出现上述问题

**Comment by qclucky7** [comment]
使用 SET NEXTTRACE_PROXY=http://127.0.0.1:1080  
这个issues提错仓库了

**Comment by tsosunchia** [comment]
> 使用 SET NEXTTRACE_PROXY=http://127.0.0.1:1080 这个issues提错仓库了

请确认，您的1080端口是否为HTTP代理而不是SOCKS

**Comment by tsosunchia** [comment]
> 这个issues提错仓库了

此仓库(NTrace-V1)是nexttrace dev仓库，所有开发工作都在这里。

**Comment by qclucky7** [comment]
检查过了, 我用的Clash，它本地代理端口http和socks都是支持的。
![image](https://github.com/nxtrace/NTrace-V1/assets/38759552/bc36daf6-6f66-4545-9e01-14065ee4ea46)

环境变量我试了http和socks都是这个错误

**Comment by tsosunchia** [comment]
> 检查过了, 我用的Clash，它本地代理端口http和socks都是支持的。 ![image](https://user-images.githubusercontent.com/38759552/283741430-bc36daf6-6f66-4545-9e01-14065ee4ea46.png)
> 
> 环境变量我试了http和socks都是这个错误

你还有其他代理软件吗，看看是否有相同的问题

我这边刚刚在linux上测试了一下没有问题

**Comment by tsosunchia** [comment]
其他人在windows上测试了，也没有复现该问题

可初步推断是Clash的问题

**Comment by qclucky7** [comment]
好的谢谢，我回去研究研究。
