### ISSUE TITLE
psize function no effect

### ISSUE THREAD

**Issue by ziojacky** [nxtrace/NTrace-dev#26]
it has no effect whether you use this function or not,package sizes are the same by default.

**Comment by tsosunchia** [comment]
使用的是ICMP MODE吗？

目前的实现在TCP MODE下，该参数似乎是有问题的。

**Comment by ziojacky** [comment]
> 使用的是ICMP MODE吗？
> 
> 目前的实现在TCP MODE下，该参数似乎是有问题的。

yes.use tcp and udp no effect,some idc icmp and tcp or udp route not same,sometime i need additional test tcp and udp,so hope you can fix this problem,thx ;)

**Comment by tsosunchia** [comment]
关于tcp mode下，我已经在payload下增加负载了，如果你那里发现psize不起作用，我这里暂时也没什么办法

**Comment by tsosunchia** [comment]
https://github.com/nxtrace/NTrace-V1/releases/tag/v1.3.1

在这个版本，该issue提到的问题，应该修复了。
