### ISSUE TITLE
map display error

### ISSUE THREAD

**Issue by BlueNoob** [nxtrace/NTrace-dev#30]
APP Referer校验失败。请检查该ak设置的白名单与访问所有的域名是否一致。详情查看：http://lbsyun.baidu.com/apiconsole/key#

NextTrace v1.2.7 2023-12-02T14:29:04Z c0455ca

**Comment by tsosunchia** [comment]
麻烦给出url

**Comment by BlueNoob** [comment]
MapTrace URL: https://assets.nxtrace.org/tracemap/c4785bed-8e5d-5e59-91bd-fa66724fbcec.html

**Comment by tsosunchia** [comment]
> MapTrace URL: https://assets.nxtrace.org/tracemap/c4785bed-8e5d-5e59-91bd-fa66724fbcec.html

我这里打开是正常的
<img width="1436" alt="image" src="https://github.com/nxtrace/NTrace-V1/assets/59512455/de6c082a-2898-4df3-8ba9-0dc6bf5df8f5">

**Comment by BlueNoob** [comment]
![image](https://github.com/nxtrace/NTrace-V1/assets/4169222/0174ccd0-07cc-4834-96ed-9af1dcaa001d)

**Comment by tsosunchia** [comment]
我这里无法复现，你可以尝试在其他设备上打开看看是什么现象

**Comment by BlueNoob** [comment]
经测试，同IP下，手机正常，PC不正常，已初步判断是adguard问题。
