### ISSUE TITLE
nexttrace 1.28 crash on Windows 7

### ISSUE THREAD

**Issue by sergeevabc** [nxtrace/NTrace-dev#35]
Windows 7 x64, nexttrace 1.28 x64.

``` console
$ nexttrace_windows_amd64.exe --version
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall()
        runtime/sys_windows_amd64.s:65 +0x75 fp=0x22fca0 sp=0x22fc80 pc=0x468bf5
rax     0x0
rbx     0xc85dc0
rcx     0x12040c0
rdi     0x7fffffdc000
rsi     0x22fea0
rbp     0x22fde0
rsp     0x22fc78
r8      0x0
r9      0x22fee0
r10     0xcd59d8
r11     0x21
r12     0x22fec0
r13     0x1
r14     0xc85340
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b
```

Let's launch version 1.27, built just a month ago. Works fine.

``` console
$ nexttrace.exe --version
NextTrace v1.2.7 2023-12-01T08:40:30Z c0455ca
NextTrace Sponsored by
· DMIT.io
· Misaka.io
· Skywolf.cloud
· Saltyfish.io
(Listed in no particular order)

NextTrace CopyRight
Honorary Founder: Leo
Project Chair: Tso
Core-Developer: Leo, Vincent, zhshch, Tso
Infra Maintainer: Tso
```

**Comment by tsosunchia** [comment]
抱歉，由于我这边没有Windows 7的测试环境，所以无法复现

**Comment by sergeevabc** [comment]
The problem is related to the fact that @golang treacherously cut off Windows 7 users starting with compiler version 1.21.

**Comment by tsosunchia** [comment]
感谢您的反馈，鉴于此程序也可以使用 golang 1.20 进行编译，建议您再尝试一下自行编译是否可以解决。

**Comment by sergeevabc** [comment]
Sorry, I'm a regular user, not a developer. I'm afraid if I start compiling the code, something will go wrong. Surely you have more experience in compiling than I do.

![2024-moscow-china-newyear](https://github.com/nxtrace/NTrace-V1/assets/373718/3fc8f416-955d-4692-bc26-3af337e4e9f8)

龙年快乐 and warm regards from Russia.

**Comment by tsosunchia** [comment]
我使用 golang 1.20.14 为你编译了一下，请尝试。
[nexttrace_windows_amd64.exe.zip](https://github.com/nxtrace/NTrace-V1/files/14232704/nexttrace_windows_amd64.exe.zip)

**Comment by sergeevabc** [comment]
I confirm that your app now works on my end as expected, thank you.

``` console
$ nexttrace.exe --version
NextTrace v1.2.8-11-g760e751 2024-02-11T14:23:40Z 760e751
NextTrace Sponsored by
· DMIT.io
· Misaka.io
· Saltyfish.io
(Listed in no particular order)

NextTrace CopyRight
Honorary Founder: Leo
Project Chair: Tso
Core-Developer: Leo, Vincent, zhshch, Tso
Infra Maintainer: Tso
```

I must not forget to run the trace with `--language en` flag, otherwise the output of the program will be in the language that I do not fully understand yet.
