### ISSUE TITLE
离线ip2region库在中国大陆地区不可下载

### ISSUE THREAD

**Issue by Error-106** [nxtrace/NTrace-dev#40]
## 本项目是基于Linux/macOS的，请确认您遇到的问题是否在Linux或macOS上存在。
是

## 你正在使用哪个版本的 nexttrace？
[27e560f](https://github.com/nxtrace/NTrace-V1/commit/27e560fbdec7d0ea8c424c5132a0cc1bc0a57066)
[main](https://github.com/nxtrace/NTrace-V1)
[windows_amd64](https://github.com/nxtrace/NTrace-V1/actions/runs/7873526637/artifacts/1238574578)

## 你看到的异常现象是什么？
离线ip2region库在中国大陆地区不可下载

## 你期待看到的正常表现是怎样的？
正常下载
此问题由ipgeo/ip2region.go line 17 中硬编码的ghproxy.com代理引起
ghproxy.com 主域名已被中国网络长城拦截,ghproxy官方推荐使用子域 mirror.ghproxy.com 具体可见ghproxy.com官网

## 请附上你的命令
N/A

## 请附上出错时软件输出的错误信息
```
Downloading DataBase...
panic: Download Failed!

goroutine 42 [running]:
github.com/nxtrace/NTrace-core/ipgeo.IP2Region({0xc00025eed0, 0xd}, 0xc0001ddfb0?, {0x0?, 0x0?}, 0x0?)
	github.com/nxtrace/NTrace-core/ipgeo/ip2region.go:53 +0x3c7
github.com/nxtrace/NTrace-core/trace.(*Hop).fetchIPData.func2()
	github.com/nxtrace/NTrace-core/trace/trace.go:192 +0x1ab
created by github.com/nxtrace/NTrace-core/trace.(*Hop).fetchIPData in goroutine 53
	github.com/nxtrace/NTrace-core/trace/trace.go:175 +0x349
```

**Comment by tsosunchia** [comment]
建议先自行下载到同目录内，URL问题将在下个版本解决，感谢反馈
