### ISSUE TITLE
Support IP2Location.io as IP geolocation data source

### ISSUE THREAD

**Issue by ip2location-com** [nxtrace/NTrace-dev#6]
We would like to recommend you to add IP2Location.io as another IP geolocation data source. It is one of the fastest API in the market using CDN. It also offer free tier for all users.

Please visit [https://www.ip2location.io](https://www.ip2location.io) for more information. We can offer PR if supported.

**Comment by tsosunchia** [comment]
We are particularly pleased to add the precise IP location information provided by IP2Location.io. However, I have a question about the API you offer. How do users utilize the free quota you provide? Do they add a token themselves, or do you offer an interface with a larger free allowance?

**Comment by ip2location-com** [comment]
Hi @tsosunchia,

The IP2Location.io Free plan supports 30,000 queries per month upon sign up with API key.

You can find more information about the API integration in https://www.ip2location.io/ip2location-documentation

**Comment by tsosunchia** [comment]
I understand what you're saying. We greatly appreciate your assistance in incorporating the precise IP location data from IP2Location.io into NextTrace's data sources. If possible, please submit a PR to the V1 repository at https://github.com/nxtrace/Ntrace-V1. The core repository is currently under reconstruction and doesn't yet have the capability to add data sources.

**Comment by tsosunchia** [comment]
We hope you can place the API Key retrieval in this file: https://github.com/nxtrace/Ntrace-V1/blob/main/ipgeo/tokens.go. This would make it convenient for users to add it as an environment variable for API usage.

**Comment by tsosunchia** [comment]
By the way, I noticed that your free plan doesn't provide much backbone network data. It would be a significant disappointment for users if this data is unavailable.

**Comment by ip2location-com** [comment]
We do provide AS number and AS name information in the free plan. Is the other information you are looking for?

**Comment by sjlleo** [comment]
> We do provide AS number and AS name information in the free plan. Is the other information you are looking for?

Thank you very much for your suggestion, but according to our statistics, many users of our API currently use far more than 30,000 times per month. We think these API usage times may not be enough for users. 

In addition, the accuracy of network requirements is very important in this project, especially the geographical location of the Chinese ISP backbone network of AS4134 AS4809 AS4837 AS9929 AS9808 AS58453 AS58807, etc. 

These geographical location accuracy determines the user's evaluation of this API Provider. If you want to submit a PR,  It is recommended that you consider it carefully.

Best Regards,
Leo Shen

**Comment by abdullahdevrel** [comment]
Hi,

I work at IPinfo.io, and I would love to throw our hat into consideration as well.

> many users of our API currently use far more than 30,000 times per month. We think these API usage times may not be enough for users.

With our API services, without even a token, users can make up to 1,000 requests per day. With a free tier account token, users can make up to 50,000 API requests/month. We offer one of the most generous free tiers in the IP geolocation industry. If users want more, they can opt to use our [free IP to Country ASN database](https://ipinfo.io/products/free-ip-database) or sign up for a premium API tier.

> backbone API data

We provide ASN data information with `org` field on the API response. Free tier API response looks like this:

```bash
curl ipinfo.io/216.248.94.153
```

Response:
```
{
  "ip": "216.248.94.153",
  "hostname": "unin-01-153-ip.dsl.netins.net",
  "city": "Marshalltown",
  "region": "Iowa",
  "country": "US",
  "loc": "42.0494,-92.9080",
  "org": "AS5056 Aureon Network Services",
  "postal": "50158",
  "timezone": "America/Chicago"
}
```

From the `org` field, you can easily extract the ASN and AS organization names. 


>  the accuracy of network requirements is very important in this project, especially the geographical location of the Chinese ISP backbone network of AS4134 AS4809 AS4837 AS9929 AS9808 AS58453 AS58807, etc.

Our IP data is backed by our [ASN database](https://ipinfo.io/products/asn-database), and looking into our code, we can clearly identify ISP backbone locations. 

```snowsql
SELECT *
FROM asn_daily
WHERE asn in ('AS4134', 'AS4809', 'AS4837', 'AS9929', 'AS9808', 'AS58453', 'AS58807')
```

![image](https://github.com/nxtrace/NTrace-V1/assets/111275753/75aab931-1c2e-4408-9d8f-04f012c439bf)

Because we use geonames.org's data, you can use a combination of HK and CN to identify Chinese ISP backbone networks.

If you are interested in making a large number of queries, I highly recommend you to check out our [free IP to Country ASN database](https://ipinfo.io/products/free-ip-database). Our databases are updated daily, we have rich technical documentation, and we have a community platform dedicated to helping OSS projects. Looking forward to your feedback.

**Comment by tsosunchia** [comment]
以下是我的个人意见（与NextTrace其他开发者无关），NextTrace是开源软件，若您不同意完全可以自己FORK一个分支。
IP2Location我认为你们策略是完全错误的，用户在不提供TOKEN直接使用你们的API时只会让用户失望。
```json5
#返回值如下
{"error":{"error_code":10000,"error_message":"Invalid API key or insufficient credit."}}
```

请看看ipinfo.io , ip-api.com 等其他GEOIP提供商的策略，他们在不提供任何TOKEN时均能为用户提供使其满意的结果，
咋就你家这么特殊呢？况且我也没感觉你们提供的信息就比其他友商更加准确，你过来提这个ISSUE的动机，
我只能怀疑为不好的原因，毕竟用户想要使用你们的GEOIP服务在NextTrace上，他们只能去你们的网站注册账号后才能享受你提到的所谓的免费额度，需要注册账号也就算了，还需要接受手机验证码验证？你们怎么敢的，来开源项目一点力也不出，只想着你们那点捞钱的事，别的普通用户会怎么想你们IP2Location，我不好说。
在彻底改变你们现在这该死的现状前，你们发一次这样的ISSUE我就喷一次。

--------------------------------
The following are my personal views and are not associated with other NextTrace developers. NextTrace is open-source, and if you disagree, you're entirely free to FORK your own branch.
Regarding IP2Location, I believe your strategy is utterly flawed. When users try to use your API without providing a TOKEN, they're bound to be disappointed.
```json5
#The response looks like this:
{"error":{"error_code":10000,"error_message":"Invalid API key or insufficient credit."}}
```
Please take a look at other GEOIP providers like ipinfo.io, ip-api.com, etc. They can provide satisfactory results to users even without any TOKEN. Why is your service so out of line? Moreover, I haven't found that the data you provide is any more accurate than your competitors. As for your motivation behind raising this ISSUE, I can't help but be skeptical. After all, if users want to use your GEOIP service on NextTrace, they have to first register on your website to enjoy the so-called 'free tier' you mentioned. Registration aside, they even have to undergo mobile verification? How dare you come to an open-source project, contribute nothing, and just focus on your money-making agenda? I won't speculate on how regular users view IP2Location, but it's not likely positive.
Until you completely rectify this atrocious situation, every time you post an ISSUE of this nature, I'll call you out.

**Comment by ip2location-com** [comment]
Thank you for your feedback. Let us share our perspective.

We have been offering a free IP geolocation API known as IPInfoDB without registration and query limits since 2010. As a pioneer, this approach is prone to abuse, as it can be used by malware and worms. Without a proper token system, distinguishing between legitimate and malicious traffic becomes impossible. This situation has raised sustainability concerns for the API, both from a technical and legal perspective.

In IP2Location.io, we have made the decision to rebuild the API from the ground up and provide support for free-tier users within acceptable use cases. NextTrace falls into this category, and we are enthusiastic about offering users free access without any concerns. SMS verification is only required when there is an elevated risk during sign-up such as from free email address. Building a verified user community is vital to ensuring a high-quality service and the long-term sustainability of the API.

Regarding your open-source concerns, we are working on a pull request (PR) to address this issue. We will submit it as soon as it's ready. The decision to discuss and accept the PR will be left to your team. We will make sure there is no commercial or upgrade required in the PR to avoid any conflicts of interest. Our priority is to offer a free API that is both valuable and stable for the internet community.

**Comment by tsosunchia** [comment]
你们公司是真的令人作呕，说一套做一套
